version: '3.8'

services:
  postgres:
    hostname: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: pet_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  spark:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_IPS=spark
      - SPARK_PUBLIC_DNS=spark
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./:/opt/bitnami/spark/scripts
    command: >
      bash -c "pip install -r /opt/bitnami/spark/scripts/requirements.txt && /opt/bitnami/scripts/spark/run.sh"
    depends_on:
      - postgres
      - clickhouse

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_IPS=spark-worker
      - SPARK_PUBLIC_DNS=spark-worker
    volumes:
      - ./:/opt/bitnami/spark/scripts
    command: >
      bash -c "pip install -r /opt/bitnami/spark/scripts/requirements.txt && /opt/bitnami/scripts/spark/run.sh"
    depends_on:
      - spark

  clickhouse:
    hostname: clickhouse
    image: clickhouse/clickhouse-server:23.8
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
  clickhouse_data: 